#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

apt-get update
apt-get install -y netcat

if ! nc -z localhost 80; then
	service nginx start

fi

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx restart
