#!/usr/bin/env bash
# Script to stop the 7-highlander process

# Find the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
    # Send a SIGTERM signal to the process to stop it
    kill -15 "$pid"
fi
