#!/usr/bin/env bash
# Script to display "To infinity and beyond" indefinitely and handle SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
