#!/usr/bin/env bash
# Bash script that:
#	Indefinitely writes 'I am alive!' to the file /tmp/my_process
#	Pauses for 2 seconds between ever 'I am alive 'txt'

while true;
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
