#!/usr/bin/env bash

while IFS=':' read -r username _ userid groupid _ home shell
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
