#!/usr/bin/env bash
# This script displays "Best School" 10 times, with "Hi" on the 9th iteration

my_variable=1
while [ $my_variable -le 10 ]
do
    if [ $my_variable -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    my_variable=$((my_variable + 1))
done
