#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash

for file in *
do
    if [[ ! -f "$file" || ${file:0:1} == "." ]]; then
        continue
    fi
    
    filename=$(echo "$file" | cut -d'-' -f2-)
    echo "$filename"
done
